name: Example
options:
  bundleIdPrefix: eu.idura
usesTabs: false
identWidth: 2
packages:
  IduraVerify:
    path: ..
targets:
  Example:
    type: application
    supportedDestinations: [iOS]
    deploymentTarget: 18.6
    sources: [Example]
    dependencies:
      - package: IduraVerify
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: "Idura Verify Example"
        INFOPLIST_KEY_UILaunchScreen_Generation[sdk=iphoneos*]: YES
        INFOPLIST_KEY_UILaunchScreen_Generation[sdk=iphonesimulator*]: YES
        