on: push

# Replace old runs in the same group
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: macos-26
    steps:
      - uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: "6.2"
      - uses: actions/checkout@v5
      - name: Cache Swift Package Manager
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
            ~/Library/Caches/org.swift.swiftpm
            ~/Library/org.swift.swiftpm  # Don't forget this!
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
      - name: Cache Xcode derived data
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-xcode-deriveddata-${{ hashFiles('**/*.xcodeproj/project.pbxproj', '**/*.xcworkspace/contents.xcworkspacedata') }}
          restore-keys: |
            ${{ runner.os }}-xcode-deriveddata-
      - name: Check formatting
        run: swift format lint . -r -s
      - name: Lint
        run: swift package plugin --allow-writing-to-package-directory swiftlint lint
      - name: Build Verify
        run: |
          xcodebuild build -quiet \
            -scheme IduraVerify -destination "platform=iOS Simulator,name=iPhone 17 Pro"
      - name: Build Examle
        working-directory: Example
        run: |
          touch Configs/config.xxconfig
          xcodebuild build -quiet \
          -scheme Example -destination "platform=iOS Simulator,name=iPhone 17 Pro"
      - name: Test
        run: |
          xcodebuild test -quiet \
            -scheme IduraVerify -destination "platform=iOS Simulator,name=iPhone 17 Pro"